% Nodes in interested network expression profiles analysis
% Plot profiles of each gene of small networkd
%%
[ fig, ngene, expr, agis ] = ...
    f_plotTable( './Process1/Profiles-DEGs-nodes-networks.csv', './OriginData/NodesForSmallNetworks.txt',...
    'Mean Plot', 'Network Analysis log', 'Plot Individually log', 'Plot Individually' );
%%
[ fig2, ngene2, expr2, agis2 ] = f_plotTable... 
    ( './Process1/Profiles-nodes-networks.csv','./OriginData/NodesForSmallNetworks.txt',...
    'Mean Plot', 'Network Analysis log', 'Plot Individually log', 'Plot Individually' );

